import os
#需要安装的库
libs = ["pyproj", "pyicu", "lief", "pymatgen", "dtaidistance", "aggdraw", "vispy", "jupyter",
        "freetypepy", "numpy", "triangle", "pygit2", "pylibjpeg", "fonttools", "lightning",
        "cx_freeze", "recordclass", "coverage", "pygresql", "mercurial", "pywinpty", "yt",
        "ets", "tifffile", "pillow", "cgohlke", "netpbmfile", "psdtagsoiffile", "sdtfile",
        "roifile", "cmapfile", "fcsfiles", "lfdfiles", "kerberos", "zeroc-ice", "caterva",
        "numba", "autobahn", "fastparquet", "cython", "ndindex", "dulwich", "pygraphviz",
        "orjson", "typed_ast", "pyzstd", "pymssql", "reportlab", "sqlalchemy", "multidict",
        "pandas", "cupy", "basemap", "cftime", "arctic", "cobra", "pytomlpp", "pyopencl",
        "regex", "scs", "frozenlist", "edt", "pymor", "pyturbojpeg", "igraph", "swiglpk",
        "fabio", "pyrsistent", "cartopy", "llvmlite", "iminuit", "scikits.odes", "ta-lib",
        "imagecodecs", "apsw", "jellyfish", "orange", "gmpy", "ecos", "bitarray", "fiona",
        "rasterio", "gdal", "ruamel.yaml", "pillow-simd", "zstd", "pygame", "kwant", "osqp",
        "kivy", "pygeos", "opencv", "pytables", "maturin", "qdldl", "pyfmi", "assimulo",
        "cantera", "sounddevice", "pydantic", "h5py", "netcdf4", "pyaudio", "shapely",
        "guiqwt", "line_profiler", "pyrxp", "glymur", "matplotlib", "cvxopt", "cvxpy",
        "py-lmdb", "psycopg", "psutil", "pycuda", "pyslalib", "pymc", "slycot", "pyspharm",
        "tomopy", "qutip", "scipy", "liblinear", "mkl-service", "mkl_fft", "mkl_random", "numexpr",
        "pycryptosat", "boost.python", "cx_logging", "scikit-learn", "pyamg", "ujson", "pytoshop",
        "pywin32", "louvain-igraph", "glfw", "discretize", "pyephem", "pymol-open-source",
        "jcc", "tinyarray", "lazy_object_proxy", "scikit-image", "lsqfit", "gvar", "cmarkgfm",
        "lxml", "gevent", "spacy", "pymongo", "spglib", "pyheif", "mistune", "xgboost", "python-ldap",
        "lz4", "aicspylibczi", "bfloat16", "mpi4py", "msgpack", "sasl", "atom", "enaml", "bottleneck",
        "simplejson", "aiohttp", "fast-histogram", "moderngl", "boost-histogram", "btrees",
        "fastcluster", "glumpy", "google-crc32c", "pyhdf", "protobuf", "udunits", "scikits.vectorplot",
        "scandir", "wordcloud", "biopython", "openexr", "pillow-avif-plugin", "imread", "traits",
        "pycares", "msvc_runtime", "statsmodels", "mahotas", "fastrlock", "pyjnius",
        "numpy-quaternion", "pylibtiff", "pyopengl", "mplcairo", "pycosat", "pycifrw",
        "rtree", "setproctitle", "pywavelets", "twainmodule", "videocapture", "vidsrc",
        "transformations", "akima", "psf", "chebyfit", "python-lzf", "numcodecs", "bitshuffle",
        "rapidjson", "indexed_gzip", "pycurl", "pyzmq", "twisted", "pycairo", "cairocffi",
        "blosc", "pyyaml", "zopflipy", "python-snappy", "brotli", "cffi", "kiwisolver",
        "fastremap", "mayavi", "vtk", "imgui", "thinc", "cytoolz", "cx_oracle", "pyerfa",
        "psygnal", "cramjam", "jpegio", "yarl", "lightgbm", "opentsne", "wrapt", "hyperspy",
        "peewee", "texture2ddecoder", "debugpy", "blis", "cymem", "murmurhash", "srsly",
        "preshed", "partseg", "param", "gitdb", "leidenalg", "blosc2", "yappi", "casa_formats_io",
        "zodbpickle", "greenlet", "thrift", "gensim", "iris", "openpiv", "numpy-stl",
        "openimageio", "icsdll", "liblas", "pyswisseph", "pystemmer", "pydde", "pykinsol",
        "pyhull", "pyemd", "pycvodes", "pycld2", "pybox2d", "py-earth", "polylearn", "planar",
        "pystruct", "pocketsphinx", "gpy", "enable", "scimath", "scikit-misc", "salientdetect",
        "curses", "stratify", "spectrum", "sima", "seqlearn", "heatmap", "hddm", "pyfltk", "libsvm",
        "cellprofiler", "medussa", "crcmod", "crc16", "sfepy", "datrie", "pylvgl", "fasttext", "sparsesvd",
        "simpleparse", "freesasa", "dukpy", "pycluster", "pycorrfit", "intbitset", "pydensecrf", "cvxcanon",
        "python-levenshtein", "lru_dict", "logbook", "kapteyn", "jsonobject", "pendulum", "openbabel", "ode",
        "obspy", "nlopt", "lp_solve", "fpzip", "pyodbc", "backports.zoneinfo", "astropy", "hdbscan", "blist",
        "bintrees", "aspell-python", "annoy", "ahds", "ad3", "dawg", "fann2", "bsddb3", "winrandom",
        "ffnet", "fdint", "flann", "fisher", "fisx", "zfec", "wrf_python", "pyminuit", "pymaxflow",
        "pyzopfli", "pyx", "pytinyexr", "pystackreg", "pymetis", "pywinhook", "python-geohash",
        "llist", "pytiff", "pycudadecon", "mod_wsgi", "marisa-trie", "tiledb", "mxnet",
        "hmmlearn", "natgrid", "cf-units", "dnacurve", "multiprocess", "uciwebauth", "molmass",
        "chaco", "holopy", "elasticdeform", "centrosome", "pyodeint", "pymvpa", "pymcubes",
        "zfpy", "simpleaudio", "python-javabridge", "grpcio", "pythonmagick", "pyalembic",
        "qdafile", "lucam", "imreg", "jpype", "pypmc", "celiagg", "naturalneighbor", "xxhash",
        "cheetah", "ceodbc", "noise", "pylzma", "python-lzo", "zope.interface", "tornado",
        "rtmidi-python", "pyasn", "persistent", "markupsafe", "netifaces", "ndimage",
        "mysqlclient", "dipy", "babel", "slideio", "bsdiff4", "bcolz", "tinybrain", "pyeda",
        "tatsu", "polygon", "fmkr", "javabridge", "pnumpy", "pythonnet", "menpo", "nitime",
        "goertzel-fft", "libsbml", "quickfix", "open3d", "xylib-py", "daal4py", "cchardet",
        "minepy", "zipline", "pulp", "simpleitk", "pytorch", "zs", "milk", "mlpy", "postgresadapter",
        "scikit-cycling", "pyqpbo", "pgmagick", "hdf5plugin", "pyfm", "pyflux", "entropy", "cyrasterize",
        "dubins", "debug-information-files", "qimage2ndarray", "imagecodecs-lite", "imaged11", "pyside",
        "pyvrml97", "pylibczi", "backports.lzma", "x86cpu", "cdecimal", "brotlipy", "fastcache", "czifile",
        "pyclearvolume", "cellcognition", "vigra", "re2", "meshpy", "scikit-fmm", "pyhook", "fasttsne",
        "rpy2", "freeimagedll", "chompack", "pysqlite", "tensorflow", "multineat", "pyfits", "grako",
        "cyordereddict", "qt_graph_helpers", "veusz", "pyqwt", "pyqt4", "trollius", "faulthandler",
        "thriftpy", "pyldap", "autopy", "jsonlib", "quantlib", "scikit-umfpack", "gr", "pyarrow",
        "python-cjson", "py_gd", "nipy", "libtfr", "mathutils", "pyfftw", "pyviennacl", "blz",
        "bigfloat", "cyassimp", "pymca", "friture", "pycogent", "blaze", "scikits.audiolab",
        "la", "bazaar", "dynd", "genshi", "python-sundials", "pyamf", "libxml-python", "pymcmc",
        "pyksvd", "pybluez", "mxbase", "libpython", "pymunk", "pygtk", "cgal-bindings",
        "bio_formats", "pysfml", "pyexiv2", "pylibdeconv", "iocbio", "pymix", "umysql",
        "lazyflow", "mmlib", "scikits.timeseries", "casuarius", "wxpython", "ilastik",
        "pywcs", "scientificpython", "vpython", "nmoldyn", "mmtk", "polymode", "scikits.delaunay",
        "cld", "py-fcm", "oursql", "py2exe", "pymutt", "carray", "llvmpy", "cgkit", "pymedia",
        "scipy-cluster", "scikits.scattpy", "scikits.samplerate", "scikits.ann", "pyxml",
        "pytst", "delny", "mysql-python", "htseq", "pyusb-ftdi", "silvercity", "steps",
        "pysparse", "pyropes", "scikits.hydroclimpy", "sendkeys", "pydbg", "pyisapie"]
#循环遍历安装
try:
	for lib in libs:
		os.system("pip install "+lib)
	print("安装成功")
except:
	for lib in libs:
		os.system("pip install -i https://pypi.tuna.tsinghua.edu.cn/simple"+lib)
	print("安装成功")